categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
  - title: '📝 Documentation & Styling'
    labels:
      - 'docs'
      - 'style'
  - title: '📚 Workflow & Infrastructure'
    labels:
      - 'refactor'
      - 'perf'
      - 'test'
      - 'build'

exclude-labels:
  - 'skip-changelog'

template: |
  ## Changelog
  $CHANGES
